[phases.setup]
nixPkgs = ['python311', 'gdal', 'proj', 'geos']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'python GOOGLE_API6_railway.py'
